### ISSUE TITLE
Besoin de plus de documentation

### ISSUE THREAD

**Issue by Gauthierrrr** [Xvirus9-dev/Pronote-Bot-DiscordJS#1]
Bonjour @Xvirus9-dev   !

Je suis interressé par votre bot Pronote, j'aimerai bien le rajouter sur mon serveur dans les prochaines semaines...
Cependant, je ne comprends pas bien son fonctionnement...

Je pense qu'il serait intéressant d'enrichir le read.me avec plusieurs points...

Par exemples comment installer les dépendences, où modifier le bot.login, le guild du serveur, les channels où s'envoient les messages, ainsi que tout simplement comment on l'utilise, quelles sont les commandes admin, les commandes utilistaeurs, etc etc...
Ou si vous préférez, simplement enregistrer votre écran (windows + g) et faire de a à z toutes les démarches pour rendre le bot fonctionnel et commet l'utiliser et poster la vidéo sur youtube en public ou en non-répertorié, et mettre le lien dans le read.me... Je pense que c'est la façon la plus rapide de faire une démo si vous n'avez pas le temps immédiatement... (je pense même que c'est d'ailleurs mieux qu'un tuto écrit) :)

J'espère que vous ferez l'un ou l'autre, j'attends votre réponse, très bonne journée !!

**Comment by alexandre-vl** [comment]
Hey, je tacherais de faire ça ^^, cependant l'api de pronote ne marche plus.
